services:
  api:
    build: ./api
    container_name: laravel-php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80" # Accès à l'API via http://localhost:8080
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql # Persistance des données
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80" # Accès via http://localhost:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
